import requests
import json
import base64

# This script requires a token from graph.microsoft.com

# Set up authentication parameters
token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6ImZiX1l6QkJRVTd4aWlVT1hBanA2Tk8tczctYlp5LURGZWxOTW9OMTA0S3MiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSIsImtpZCI6IkpZaEFjVFBNWl9MWDZEQmxPV1E3SG4wTmVYRSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yNTkwY2NlZi02ODdkLTQ5M2ItYWU4ZC00NDFjYmFiNjNhNzIvIiwiaWF0IjoxNzU1ODgxMTIxLCJuYmYiOjE3NTU4ODExMjEsImV4cCI6MTc1NTg4NTY1NSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhaQUFBQTYvdkRzTUFNOVhsM1FHeXdCclJDSVNkbm90V2FVWmFTYkRuNHFKdnkwWGpKT3VOd0NoaUg1ZENRSU15UkhIUnRSQVY3aXN6cWhHT2pzd2ljQStQbFNBPT0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik1pY3Jvc29mdCBPZmZpY2UiLCJhcHBpZCI6ImQzNTkwZWQ2LTUyYjMtNDEwMi1hZWZmLWFhZDIyOTJhYjAxYyIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiV2lsbGlhbXMiLCJnaXZlbl9uYW1lIjoiU3VuaXRhIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiOTcuOTEuMjE3LjQiLCJuYW1lIjoiU3VuaXRhIFdpbGxpYW1zIiwib2lkIjoiNGU3OTA4NWYtNmY1ZC00ZjM3LWJjODctOWVhNzBmYTlmOTdiIiwicGxhdGYiOiI4IiwicHVpZCI6IjEwMDMyMDAzNjA1NDJBQTIiLCJyaCI6IjEuQVU0QTc4eVFKWDFvTzBtdWpVUWN1clk2Y2dNQUFBQUFBQUFBd0FBQUFBQUFBQUFPQWJST0FBLiIsInNjcCI6IkF1ZGl0TG9nLkNyZWF0ZSBDYWxlbmRhci5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlIERhdGFMb3NzUHJldmVudGlvblBvbGljeS5FdmFsdWF0ZSBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgZW1haWwgRmlsZXMuUmVhZCBGaWxlcy5SZWFkLkFsbCBGaWxlcy5SZWFkV3JpdGUuQWxsIEZpbGVTdG9yYWdlQ29udGFpbmVyLlNlbGVjdGVkIEdyb3VwLlJlYWQuQWxsIEdyb3VwLlJlYWRXcml0ZS5BbGwgSW5mb3JtYXRpb25Qcm90ZWN0aW9uUG9saWN5LlJlYWQgTWFpbC5SZWFkV3JpdGUgTWFpbC5TZW5kIE5vdGVzLkNyZWF0ZSBvcGVuaWQgT3JnYW5pemF0aW9uLlJlYWQuQWxsIFBlb3BsZS5SZWFkIFBlb3BsZS5SZWFkLkFsbCBQcmludGVyLlJlYWQuQWxsIFByaW50ZXJTaGFyZS5SZWFkQmFzaWMuQWxsIFByaW50Sm9iLkNyZWF0ZSBQcmludEpvYi5SZWFkV3JpdGVCYXNpYyBwcm9maWxlIFJlcG9ydHMuUmVhZC5BbGwgU2Vuc2l0aXZlSW5mb1R5cGUuRGV0ZWN0IFNlbnNpdGl2ZUluZm9UeXBlLlJlYWQuQWxsIFNlbnNpdGl2aXR5TGFiZWwuRXZhbHVhdGUgVGFza3MuUmVhZFdyaXRlIFRlYW1NZW1iZXIuUmVhZFdyaXRlLkFsbCBUZWFtc1RhYi5SZWFkV3JpdGVGb3JDaGF0IFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXJzLlJlYWQiLCJzaWQiOiIwMDdkNzU0OS0zZjY2LWYzY2YtMTU2OS1lZmQxZTM2Y2RmM2YiLCJzdWIiOiJCT01KOXZVSWtNb3hCVXRoS2VnRjdqTGl6Y0swbXJ1N2NKWU9uN20wN2RZIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiMjU5MGNjZWYtNjg3ZC00OTNiLWFlOGQtNDQxY2JhYjYzYTcyIiwidW5pcXVlX25hbWUiOiJTdW5pdGEuV2lsbGlhbXNAbWVnYWJpZ3RlY2guY29tIiwidXBuIjoiU3VuaXRhLldpbGxpYW1zQG1lZ2FiaWd0ZWNoLmNvbSIsInV0aSI6Ik9MTEJPbEtNZzBhblhSODgzdEFwQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfZnRkIjoiQjRsZTROVXFYR2VPaHJFVDRpeXB2SU83R2tubmlUN3J2V1VJamZHeXhRTUJaWFZ5YjNCbGJtOXlkR2d0WkhOdGN3IiwieG1zX2lkcmVsIjoiMSA4IiwieG1zX3N0Ijp7InN1YiI6InRaaGFlcC02RGtFS3dVT3lOUTdCM3kyZnZpWHpNODdYRjR0bE0tMEpaQzAifSwieG1zX3RjZHQiOjE2NzEzMTExODJ9.LwgzlgQBAZs-404UQG78a0J1D_ovGPC7t71BzxPE8MEJuRxoFI_ENKYjU-xo7c1SwokfM_3QVXMTB4ezOtx-uDXvV9T-U_lGhWosEBCzkgVbSEvY2MP3uNx_X_GZuclhG0KSQEc0tceULIwst3AKiBN_6NO_EI6y6_gMI_-AdqXnQ1DBrP7r6Q0NvpB8uciuA5zwC85Z0QXFukG5_i0ZiQW4juVGCOIMtJMJLtwVDjHajI81PzJkz76i4MhPJPO8Uk61wGuByfXg-63zL7H5SC2mEm7EGQlgOtE83XBe3m3RZ8tmHl02Mrd3wd8UYLv3BdFks22_fAuX26MISBTqqA"

headers = {
    'Authorization': 'Bearer ' + token,
    'Content-Type': 'application/json'
}

# Define the endpoint to retrieve emails
endpoint = 'https://graph.microsoft.com/v1.0/me/messages?$select=subject,body'

# Send a GET request to the endpoint to retrieve emails
response = requests.get(endpoint, headers=headers)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    data = json.loads(response.text)
    # Iterate through each email in the response
    for email in data['value']:
        # Get the email subject and body
        subject = email['subject']
        body = email['body']['content']
        # Check if the email has an HTML body
        if email['body']['contentType'] == 'html':
            # Save the HTML body to a file
            with open(subject + '.html', 'w') as f:
                f.write(body)
            print('HTML email downloaded:', subject + '.html')
    print('All emails downloaded.')
else:
    print('Error retrieving emails:', response.text)

